<?php

namespace Database\Seeders;

use App\Models\EwasteItem;
use Illuminate\Database\Seeder;

class EwasteItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'name' => 'Mobile Phone',
                'ai_class_name' => 'phone',
                'category_name' => 'Small Electronics',
                'avg_weight_kg' => 0.20,
                'min_weight_kg' => 0.15,
                'max_weight_kg' => 0.35,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Laptop',
                'ai_class_name' => 'laptop',
                'category_name' => 'Computers',
                'avg_weight_kg' => 2.50,
                'min_weight_kg' => 1.50,
                'max_weight_kg' => 4.00,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Desktop CPU',
                'ai_class_name' => 'desktop_cpu',
                'category_name' => 'Computers',
                'avg_weight_kg' => 8.00,
                'min_weight_kg' => 5.00,
                'max_weight_kg' => 12.00,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Monitor',
                'ai_class_name' => 'monitor',
                'category_name' => 'Screens',
                'avg_weight_kg' => 4.00,
                'min_weight_kg' => 2.50,
                'max_weight_kg' => 8.00,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Television',
                'ai_class_name' => 'tv',
                'category_name' => 'Screens',
                'avg_weight_kg' => 10.00,
                'min_weight_kg' => 5.00,
                'max_weight_kg' => 25.00,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Keyboard',
                'ai_class_name' => 'keyboard',
                'category_name' => 'Computer Accessories',
                'avg_weight_kg' => 0.80,
                'min_weight_kg' => 0.40,
                'max_weight_kg' => 1.20,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Mouse',
                'ai_class_name' => 'mouse',
                'category_name' => 'Computer Accessories',
                'avg_weight_kg' => 0.20,
                'min_weight_kg' => 0.10,
                'max_weight_kg' => 0.35,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Printer',
                'ai_class_name' => 'printer',
                'category_name' => 'Office Electronics',
                'avg_weight_kg' => 8.00,
                'min_weight_kg' => 4.00,
                'max_weight_kg' => 18.00,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Speaker',
                'ai_class_name' => 'speaker',
                'category_name' => 'Audio Electronics',
                'avg_weight_kg' => 1.00,
                'min_weight_kg' => 0.30,
                'max_weight_kg' => 4.00,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Remote Control',
                'ai_class_name' => 'remote_control',
                'category_name' => 'Small Electronics',
                'avg_weight_kg' => 0.20,
                'min_weight_kg' => 0.10,
                'max_weight_kg' => 0.35,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Cable',
                'ai_class_name' => 'cable',
                'category_name' => 'Cables',
                'avg_weight_kg' => 0.12,
                'min_weight_kg' => 0.05,
                'max_weight_kg' => 0.30,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Cable Batch',
                'ai_class_name' => 'cable_batch',
                'category_name' => 'Cables',
                'avg_weight_kg' => 8.00,
                'min_weight_kg' => 3.00,
                'max_weight_kg' => 20.00,
                'price_per_kg' => 700,
                'is_batch' => true,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Charger',
                'ai_class_name' => 'charger',
                'category_name' => 'Power Accessories',
                'avg_weight_kg' => 0.30,
                'min_weight_kg' => 0.15,
                'max_weight_kg' => 0.60,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Power Adapter',
                'ai_class_name' => 'power_adapter',
                'category_name' => 'Power Accessories',
                'avg_weight_kg' => 0.35,
                'min_weight_kg' => 0.15,
                'max_weight_kg' => 0.80,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Router / Modem',
                'ai_class_name' => 'router',
                'category_name' => 'Network Electronics',
                'avg_weight_kg' => 0.50,
                'min_weight_kg' => 0.25,
                'max_weight_kg' => 1.20,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Battery',
                'ai_class_name' => 'battery',
                'category_name' => 'Hazardous Components',
                'avg_weight_kg' => 1.20,
                'min_weight_kg' => 0.20,
                'max_weight_kg' => 5.00,
                'price_per_kg' => 700,
                'is_batch' => false,
                'is_hazardous' => true,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Circuit Board',
                'ai_class_name' => 'circuit_board',
                'category_name' => 'Electronic Boards',
                'avg_weight_kg' => 0.20,
                'min_weight_kg' => 0.05,
                'max_weight_kg' => 0.80,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Hard Disk',
                'ai_class_name' => 'hard_disk',
                'category_name' => 'Computer Storage',
                'avg_weight_kg' => 0.50,
                'min_weight_kg' => 0.20,
                'max_weight_kg' => 0.80,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Tablet',
                'ai_class_name' => 'tablet',
                'category_name' => 'Small Electronics',
                'avg_weight_kg' => 0.60,
                'min_weight_kg' => 0.30,
                'max_weight_kg' => 1.00,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Torch / Flashlight',
                'ai_class_name' => 'torch',
                'category_name' => 'Small Electronics',
                'avg_weight_kg' => 0.45,
                'min_weight_kg' => 0.15,
                'max_weight_kg' => 1.20,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Watch / Small Clock',
                'ai_class_name' => 'watch',
                'category_name' => 'Small Electronics',
                'avg_weight_kg' => 0.25,
                'min_weight_kg' => 0.08,
                'max_weight_kg' => 0.70,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Soldering Iron',
                'ai_class_name' => 'soldering_iron',
                'category_name' => 'Electronic Tools',
                'avg_weight_kg' => 0.40,
                'min_weight_kg' => 0.20,
                'max_weight_kg' => 1.00,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Game Controller / Joystick',
                'ai_class_name' => 'game_controller',
                'category_name' => 'Small Electronics',
                'avg_weight_kg' => 0.35,
                'min_weight_kg' => 0.15,
                'max_weight_kg' => 0.80,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Mixed Small Electronics Batch',
                'ai_class_name' => 'mixed_small_electronics_batch',
                'category_name' => 'Mixed E-Waste',
                'avg_weight_kg' => 20.00,
                'min_weight_kg' => 8.00,
                'max_weight_kg' => 50.00,
                'price_per_kg' => 700,
                'is_batch' => true,
                'requires_staff_verification' => true,
            ],
            [
                'name' => 'Unknown Mixed E-Waste Pile',
                'ai_class_name' => 'unknown_mixed_ewaste_pile',
                'category_name' => 'Mixed E-Waste',
                'avg_weight_kg' => 20.00,
                'min_weight_kg' => 5.00,
                'max_weight_kg' => 60.00,
                'price_per_kg' => 700,
                'is_batch' => true,
                'requires_staff_verification' => true,
                'notes' => 'Used when model sees dense mixed pile but cannot classify individual objects yet.',
            ],
            [
                'name' => 'Unknown Electronic Item',
                'ai_class_name' => 'unknown_electronic_item',
                'category_name' => 'Unknown E-Waste',
                'avg_weight_kg' => 1.00,
                'min_weight_kg' => 0.20,
                'max_weight_kg' => 5.00,
                'price_per_kg' => 700,
                'is_batch' => false,
                'requires_staff_verification' => true,
                'notes' => 'Used when item is visible but the model cannot confidently classify it.',
            ],
        ];

        foreach ($items as $item) {
            EwasteItem::updateOrCreate(
                ['ai_class_name' => $item['ai_class_name']],
                array_merge([
                    'price_per_item' => null,
                    'is_hazardous' => false,
                    'status' => 'active',
                    'notes' => null,
                ], $item)
            );
        }
    }
}
